# Generated by Django 5.1.3 on 2025-11-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
            ],
        ),
    ]
