# Generated by Django 5.2.4 on 2025-11-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_careers_chat_message_plans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Careers',
            new_name='Carriers',
        ),
    ]
