# Generated by Django 5.1.3 on 2025-11-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0004_rename_careers_carriers"),
    ]

    operations = [
        migrations.AddField(
            model_name="plans",
            name="details",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plans",
            name="tagline1",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plans",
            name="tagline2",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
