# Generated by Django 5.1.3 on 2025-11-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0005_plans_details_plans_tagline1_plans_tagline2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payasyougo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zipcode", models.CharField(max_length=200)),
                ("e_id", models.CharField(max_length=200)),
                ("plan_id", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("contact_no", models.CharField(max_length=200)),
                ("sim_type", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="plans",
            name="live_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plans",
            name="plan_id",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="plans",
            name="company_id",
            field=models.CharField(max_length=200),
        ),
    ]
