# Generated by Django 5.2.6 on 2025-11-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_payasyougo_plans_live_status_plans_plan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='user_type',
            field=models.CharField(default='user', max_length=200),
        ),
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(default=None, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
