# Generated by Django 5.2.6 on 2025-11-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_signup_user_type_signup_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
