# Generated by Django 5.1.3 on 2025-11-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0009_alter_signup_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carrier_id", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("phone_no", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=200)),
                ("request_topup", models.CharField(max_length=200)),
                ("pending_status", models.BooleanField(default=True)),
            ],
        ),
    ]
