# Generated by Django 5.1.3 on 2025-11-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0010_topup"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topup",
            old_name="carrier_id",
            new_name="company_id",
        ),
    ]
