# Generated by Django 5.1.3 on 2025-11-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0011_rename_carrier_id_topup_company_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account_balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                (
                    "account_balance_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("last_updated", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Activate_sim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activation_id", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=200)),
                ("plan_id", models.CharField(max_length=200)),
                ("phone_no", models.CharField(max_length=200)),
                (
                    "amount_charged",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("offer", models.CharField(max_length=2000)),
                ("pending", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recharge_id", models.CharField(max_length=200, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_screenshot", models.CharField(max_length=2000)),
                ("approved", models.BooleanField(default=False)),
                ("username", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
