# Generated by Django 5.1.3 on 2025-11-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0012_account_balance_activate_sim_recharge"),
    ]

    operations = [
        migrations.AddField(
            model_name="activate_sim",
            name="balance_history",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recharge",
            name="balance_history",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topup",
            name="balance_history",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
