# Generated by Django 5.1.3 on 2025-11-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0013_activate_sim_balance_history_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topup",
            name="balance_history",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
