# Generated by Django 5.1.3 on 2025-11-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0014_alter_topup_balance_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("history_type", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("history_message", models.TextField()),
                (
                    "history_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
