# Generated by Django 5.2.6 on 2025-11-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0015_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges_and_Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('topup_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recharge_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sim_activation_charges', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
