# Generated by Django 5.1.3 on 2025-11-17 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0016_charges_and_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="activate_sim",
            name="email",
            field=models.CharField(default=None, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activate_sim",
            name="postal_code",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topup",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
