# Generated by Django 5.2.6 on 2025-11-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0017_activate_sim_email_activate_sim_postal_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topup',
            name='pending_status',
        ),
        migrations.AddField(
            model_name='topup',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
