# Generated by Django 5.1.3 on 2025-11-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0018_remove_topup_pending_status_topup_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="activate_sim",
            name="company_id",
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name="activate_sim",
            name="eid",
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name="activate_sim",
            name="emi",
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name="activate_sim",
            name="iccid",
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name="charges_and_discount",
            name="discounts",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
