# Generated by Django 5.1.3 on 2025-11-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0019_activate_sim_company_id_activate_sim_eid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="charges_and_discount",
            old_name="discounts",
            new_name="recharge_discount",
        ),
        migrations.AddField(
            model_name="charges_and_discount",
            name="sim_activation_discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="charges_and_discount",
            name="topup_discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
