# Generated by Django 5.1.3 on 2025-11-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend_app",
            "0020_rename_discounts_charges_and_discount_recharge_discount_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payasyougo",
            name="email",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
