# Generated by Django 5.1.3 on 2025-11-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0021_alter_payasyougo_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("plan_id", models.CharField(max_length=200)),
            ],
        ),
    ]
