# Generated by Django 5.1.3 on 2025-11-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0022_offers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Default_charged_discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_id", models.CharField(max_length=200)),
                ("company_id", models.CharField(max_length=200)),
                ("topup_charges", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "recharge_charges",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "sim_activation_charges",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "topup_discount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "recharge_discount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "sim_activation_discount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.AddField(
            model_name="topup",
            name="payable_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
