# Generated by Django 5.2.6 on 2025-11-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0023_default_charged_discount_topup_payable_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Offers',
            new_name='Plan_offers',
        ),
        migrations.RemoveField(
            model_name='charges_and_discount',
            name='sim_activation_charges',
        ),
        migrations.RemoveField(
            model_name='charges_and_discount',
            name='sim_activation_discount',
        ),
        migrations.RemoveField(
            model_name='charges_and_discount',
            name='topup_charges',
        ),
        migrations.RemoveField(
            model_name='charges_and_discount',
            name='topup_discount',
        ),
        migrations.RemoveField(
            model_name='default_charged_discount',
            name='sim_activation_charges',
        ),
        migrations.RemoveField(
            model_name='default_charged_discount',
            name='sim_activation_discount',
        ),
        migrations.RemoveField(
            model_name='default_charged_discount',
            name='topup_charges',
        ),
        migrations.RemoveField(
            model_name='default_charged_discount',
            name='topup_discount',
        ),
        migrations.AddField(
            model_name='carriers',
            name='esim_required_fields',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='carriers',
            name='physical_required_fields',
            field=models.JSONField(default=list),
        ),
    ]
