# Generated by Django 5.2.6 on 2025-11-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0024_company_offers_rename_offers_plan_offers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activate_sim',
            name='offer',
        ),
    ]
