# Generated by Django 5.2.6 on 2025-11-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0025_remove_activate_sim_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='activate_sim',
            name='pin_code',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
