# Generated by Django 5.2.6 on 2025-11-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0026_activate_sim_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
