# Generated by Django 5.2.6 on 2025-11-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0027_recharge_payable_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='activate_sim',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
