# Generated by Django 5.2.6 on 2025-11-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0028_activate_sim_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_balance',
            name='account_balance_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
