# Generated by Django 5.2.6 on 2025-11-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0029_alter_account_balance_account_balance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='activate_sim',
            name='sim_type',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
