# Generated by Django 5.2.6 on 2025-12-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0030_activate_sim_sim_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activate_sim',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='recharge',
            name='approved',
        ),
        migrations.AddField(
            model_name='activate_sim',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='recharge',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
