# Generated by Django 5.2.6 on 2026-02-06 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend_app",
            "0031_remove_activate_sim_pending_remove_recharge_approved_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to="backend_app.signup",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to="backend_app.signup",
            ),
        ),
    ]
