# Generated by Django 5.2.6 on 2026-02-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0032_message_receiver_alter_message_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="carriers",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plans",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
