# Generated by Django 5.2.6 on 2026-02-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0033_carriers_is_deleted_plans_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="plans",
            name="carrier_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
